### ISSUE TITLE
How launch url in browser ?

### ISSUE THREAD

**Issue by poorvajappja** [gluonhq/gluon-samples#104]
In android I code like this 

    Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.google.com"));       startActivity(browserIntent); 

How can I do this in javafx for android?

**Comment by jperedadnr** [comment]
Attach has a [BrowserService](https://github.com/gluonhq/attach/tree/master/modules/browser) just for this.

**Comment by poorvajappja** [comment]
@jperedadnr I can't understand. Can you explain in detail?

**Comment by tiainen** [comment]
You can read the documentation on how to use services here: https://docs.gluonhq.com/#_device_interface
The javadoc for the BrowserService is here: https://docs.gluonhq.com/attach/javadoc/latest/com.gluonhq.attach.browser/com/gluonhq/attach/browser/BrowserService.html
