### ISSUE TITLE
Melts my MacBook Pro

### ISSUE THREAD

**Issue by deontologic** [gluonhq/gluon-samples#11]
I didn't want to install any IDE plugins so I tried running the gluonVM demo from this repo; I had to kill after 10 minutes of max CPU use...

> Task :singleview-gluonvmApp:launchIPhoneSimulator 
Setting gloal LogLevel to INFO
Configure logging for GVM tooling... BUNDLE ID = com.gluonhq.samples.singleviewgvm.SingleViewWithGluonVM
[HIGGS] Creating higgs...
[20:24:34:500] com.gluonhq.higgs.Higgs: [HIGGS] mainClassName = com/gluonhq/samples/singleviewgvm/SingleViewWithGluonVM 
[20:24:34:500] com.gluonhq.higgs.Higgs: [HIGGS] mainClassName = com/gluonhq/samples/singleviewgvm/SingleViewWithGluonVM 
[20:24:34:502] com.gluonhq.higgs.Higgs: [HIGGS] arch = x86_64 
[20:24:34:502] com.gluonhq.higgs.Higgs: [HIGGS] arch = x86_64 
missing file /Users/august/Documents/prog/test-projects/gluon-samples/singleview-gluonvm/singleview-gluonvmApp/build/classes/java/ios
Warning: netscape.javascript.JSObject is a phantom class!
Warning: javax.xml.bind.annotation.XmlTransient is a phantom class!
Warning: javax.xml.bind.annotation.XmlElement is a phantom class!
Warning: java.awt.datatransfer.Clipboard is a phantom class!
Warning: java.util.prefs.Preferences is a phantom class!
Warning: java.awt.datatransfer.Transferable is a phantom class!
Warning: java.awt.datatransfer.DataFlavor is a phantom class!
Warning: java.awt.datatransfer.FlavorMap is a phantom class!
Warning: java.awt.datatransfer.ClipboardOwner is a phantom class!
Warning: java.awt.datatransfer.StringSelection is a phantom class!
Warning: javax.script.ScriptEngine is a phantom class!
Warning: javax.script.ScriptEngineManager is a phantom class!
Warning: javax.script.Bindings is a phantom class!
Warning: javax.script.SimpleBindings is a phantom class!
Warning: java.util.prefs.BackingStoreException is a phantom class!
<===========--> 87% EXECUTING [9m 40s]
> :singleview-gluonvmApp:launchIPhoneSimulator
> IDLE
> IDLE
> IDLE
^Csingleview-gluonvm $

**Comment by jperedadnr** [comment]
The very first time you run Gluon VM, it goes through the whole process of ahead-of-time compiling all the Java modules, so it really takes a long time (talking about maybe 20 minutes in a MacBook Pro).  So you should let it finish. If you have memory issues along the process, run it again, but consider the memory tip [here](https://github.com/javafxports/javafxmobile-plugin/blob/master/README.md#ios).

The good news is that everything is cached (see ~/.gvm/aot), and the next run will be way shorter. If you make a change in your project, it will have to compile just the project, so it should take less than 2 minutes.

If this works for you, feel free to close this issue.

**Comment by deontologic** [comment]
Had to run for an additional ten minutes, but it works. Thanks!
