### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by Kal-ernest** [gluonhq/gluon-samples#119]
Build failure and error atributed to :Missing library libjvm.a not in linkpath
[HelloFXlog.txt](https://github.com/gluonhq/gluon-samples/files/7026097/HelloFXlog.txt)

**Comment by ctoabidmaqbool** [comment]
@Kal-ernest I am unsure, but maybe can helps you.
See If you already have requirements already e.g. https://docs.gluonhq.com/#platforms_linux
Use Latest GraalVM if not already e.g. [GraalVM CE Gluon 21.2.0-dev-20210621_1207](https://github.com/gluonhq/graal/releases/tag/gluon-21.2.0-dev-20210621_1207)
```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM 21.2.0-dev (build 11.0.11+8-jvmci-21.2-b02)
OpenJDK 64-Bit Server VM GraalVM 21.2.0-dev (build 11.0.11+8-jvmci-21.2-b02, mixed mode, sharing)
```
Hope your gluonfx-maven-plugin will be latest too e.g. 1.0.4

**Comment by Kal-ernest** [comment]
Thanks @ctoabidmaqbool . Using GraalVM CE Gluon 21.2.0-dev-20210621_1207 fixed it. I was using graalvm-ce-java11-linux-amd64-21.2.0 instead, which brought errors.

**Comment by SaptarshiSarkar12** [comment]
@Kal-ernest @ctoabidmaqbool I tried using Gluon's GraalVM for JDK 23, but workflow still failed. Can anyone please help me out?
The error message occurred only for Ubuntu:
```css
java.io.IOException: Missing library libjvm.a not in linkpath /opt/hostedtoolcache/GraalVM/gluon-23+25.1-dev-2409082136.0/x86_64/lib/svm/clibraries/linux-amd64
```

Here's the logs: https://github.com/SaptarshiSarkar12/Drifty/actions/runs/13470927888/job/37644327121#step:16:3648

**Comment by ctoabidmaqbool** [comment]
@SaptarshiSarkar12 I am not sure, why it's looking for `libjvm.a` in wrong location, I have to dig-up deeply!
However `libjvm.a` is in a further subdirectory as you can see:

```
$ pwd
/mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev/lib/svm/clibraries/linux-amd64

$ tree
.
├── glibc
│   ├── libjvm.a
│   └── liblibchelper.a
└── musl
    ├── libjvm.a
    └── liblibchelper.a

3 directories, 4 files
```

**Comment by SaptarshiSarkar12** [comment]
I see. @ctoabidmaqbool Thank you for deep diving into the issue 😁.
Then, most probably the issue is with the gluonfx-maven plugin as it checks in the wrong location, isn't it?

**Comment by SaptarshiSarkar12** [comment]
What should I do from my end to make it work again?

**Comment by SaptarshiSarkar12** [comment]
So, I just checked now. I was using 1.0.23 version of the plugin. Let me check with the latest 1.0.25 version.

**Comment by SaptarshiSarkar12** [comment]
I upgraded to 1.0.25 but I'm encountering this error in my local machine (Ubuntu):
```prolog
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.24:runagent (default-cli) on project GUI: Error creating Substrate Dispatcher: Error downloading zips: java.io.IOException: Error downloading link from https://github.com/gluonhq/vmone/releases/download/gvm-24-2/vmone-linux-x64.zip. Unexpected status code: 404 -> [Help 1]
```
![Error Screenshoot](https://github.com/user-attachments/assets/1e451d6a-33e2-4089-b8b7-260afc3196d6)

@ctoabidmaqbool I visited the link but there is no repo with that name 😢. What to do then?

**Comment by SaptarshiSarkar12** [comment]
@jperedadnr @abhinayagarwal Please check this major issue for missing vmone repo ☝.

**Comment by ctoabidmaqbool** [comment]
> [@jperedadnr](https://github.com/jperedadnr) [@abhinayagarwal](https://github.com/abhinayagarwal) Please check this major issue for missing vmone repo ☝.

The [`vmone`](https://github.com/gluonhq/vmone) repo was archived for a period of time and was later reopened. However, it's currently no longer in use. The GluonFX team was experimenting with it, but it seems that the `vmone` approach did not fully meet all requirements.

GluonFX plugin versions `1.0.24` and `1.0.25` were dependent on GraalVM 23+ and `vmone`, but this has now been reverted. As of version `1.0.26`, GluonFX no longer uses `vmone` and instead depends on GraalVM 17+.

For more context, you can refer to the detailed discussion here: https://github.com/gluonhq/gluonfx-maven-plugin/issues/518
