### ISSUE TITLE
fatal error LNK1120: 2 unresolved externals

### ISSUE THREAD

**Issue by YepYuYu** [gluonhq/gluon-samples#128]
use gluonfx:build

gluonfx-maven-plugin:1.0.7
maven-compiler-plugin:3.8.1

Native Image (org.graalvm.native-image, version 22.0.0-dev)

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 22.0.0-dev (build 11.0.12+5-jvmci-21.3-b03)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0-dev (build 11.0.12+5-jvmci-21.3-b03, mixed mode, sharing)

Microsoft (R) Incremental Linker Version 14.16.27045.0

**Comment by jperedadnr** [comment]
Please provide a detailed error.
