### ISSUE TITLE
App ios crash immediately

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluon-samples#134]
After executing the commands ./gradlew nativeBuild, ./gradlew nativaPackage, I run the command ./gradlew nativeRun on the mac but the app crashes immediately after a few seconds of loading.
Attached is the build.gradle file and the log
[build_gradle.txt](https://github.com/gluonhq/gluon-samples/files/7972208/build_gradle.txt)
[IosLog.txt](https://github.com/gluonhq/gluon-samples/files/7972209/IosLog.txt)

**Comment by jperedadnr** [comment]
Remove
```
compile group: 'org.openjfx', name: 'javafx-controls', version: '12'
```
from your build.gradle,  uninstall the app from your device, and then run:
```
./gradlew nativeBuild nativePackage nativeInstall nativeRun
```
If it still fails post all the logs from the process.

**Comment by websystemtechnology** [comment]
After performing the steps of the previous post, the app still goes in eror, this is the complete log:

[ErroreIOS.txt](https://github.com/gluonhq/gluon-samples/files/7978876/ErroreIOS.txt)

**Comment by websystemtechnology** [comment]
Ok, solved. Thank you
