### ISSUE TITLE
not support  Java 17?

### ISSUE THREAD

**Issue by mylovetop** [gluonhq/gluon-samples#149]
Default icon.ico image generated in D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gensrc\windows\assets.
Consider copying it to D:\down\gluon-samples-master\gluon-samples-master\GoNative\src\windows before performing any modification
java.io.IOException: Cannot run program "rc": CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at com.gluonhq.substrate.util.ProcessRunner.setupProcess(ProcessRunner.java:378)
        at com.gluonhq.substrate.util.ProcessRunner.runProcess(ProcessRunner.java:236)
        at com.gluonhq.substrate.util.ProcessRunner.runProcess(ProcessRunner.java:222)
        at com.gluonhq.substrate.target.WindowsTargetConfiguration.createIconResource(WindowsTargetConfiguration.java:261)
        at com.gluonhq.substrate.target.WindowsTargetConfiguration.link(WindowsTargetConfiguration.java:222)
        at com.gluonhq.substrate.SubstrateDispatcher.nativeLink(SubstrateDispatcher.java:443)
        at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:47)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

evn:

[Mon Jun 27 19:28:01 CST 2022][INFO] [SUB]  Version info: 'GraalVM 22.1.0 Java 17 CE'
[Mon Jun 27 19:28:01 CST 2022][INFO] [SUB]  C compiler: cl.exe (microsoft, x64, 19.16.27048)
[Mon Jun 27 19:28:01 CST 2022][INFO] [SUB]  Garbage collector: Serial GC

thank you

**Comment by jperedadnr** [comment]
Are you running from the x64 terminal (x64 Native Tools Command Prompt for VS)?

**Comment by mylovetop** [comment]
thank You

![image](https://user-images.githubusercontent.com/1885713/176060674-3cd38f0b-49f3-409a-839f-537ebf4305fc.png)

![image](https://user-images.githubusercontent.com/1885713/176061057-7baa60e2-0872-4c67-835f-5576e011e9a6.png)


use powershell complie
the error log: 

Process
=======
compile

Command Line
============
D:\app\jdk\graalvm\graalvm-ce-java17-22.1.0\bin\native-image.cmd "-Djdk.internal.lambda.eagerlyInitialize=false" --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExceptionStackTraces -H:-DeadlockWatchdogExitOnTimeout "-H:DeadlockWatchdogInterval=0" -H:+RemoveSaturatedTypeFlows "--features=org.graalvm.home.HomeFinderFeature" "-H:TempDirectory=D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp" "-H:EnableURLProtocols=http,https" "-H:ReflectionConfigurationFiles=D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\reflectionconfig-x86_64-windows.json" "-H:JNIConfigurationFiles=D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\jniconfig-x86_64-windows.json" "-H:ResourceConfigurationFiles=D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\resourceconfig-x86_64-windows.json" "-H:IncludeResourceBundles=com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle,com/sun/glass/ui/win/themes" "-Dsvm.platform=org.graalvm.nativeimage.Platform$WINDOWS_AMD64" -cp "C:\Users\hope\.m2\repository\com\gluonhq\substrate\0.0.54\substrate-0.0.54.jar;D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\classpathJar.jar" com.gluonhq.samples.gonative.GoNative

Output
======
Warning: Ignoring server-mode native-image argument --no-server.
========================================================================================================================
GraalVM Native Image: Generating 'com.gluonhq.samples.gonative.gonative' (shared library)...
========================================================================================================================

[1/7] Initializing...                                                                                    (0.0s @ 0.09GB)
Error: Error compiling query code (in D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '-ID:\app\jdk\graalvm\graalvm-ce-java17-22.1.0\include\win32' '/FeD:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.exe' 'D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.c'' output included error: [JNIHeaderDirectives.c, Microsoft (R) Incremental Linker Version 14.16.27048.0, Copyright (C) Microsoft Corporation.  All rights reserved., , /out:D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.exe , JNIHeaderDirectives.obj , libucrt.lib(exit.obj) : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64']
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '-ID:\app\jdk\graalvm\graalvm-ce-java17-22.1.0\include\win32' '/FeD:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.exe' 'D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.c'' output included error: [JNIHeaderDirectives.c, Microsoft (R) Incremental Linker Version 14.16.27048.0, Copyright (C) Microsoft Corporation.  All rights reserved., , /out:D:\down\gluon-samples-master\gluon-samples-master\GoNative\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1656375702760\JNIHeaderDirectives.exe , JNIHeaderDirectives.obj , libucrt.lib(exit.obj) : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64']
	at com.oracle.svm.core.util.UserError.abort(UserError.java:138)
	at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:371)
	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1623)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1065)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
------------------------------------------------------------------------------------------------------------------------
                         0.1s (3.9% of total time) in 8 GCs | Peak RSS: 0.68GB | CPU load: 7.27
========================================================================================================================
Failed generating 'com.gluonhq.samples.gonative.gonative' after 2.1s.
Error: Image build request failed with exit status 1


Result
======
result: 1

**Comment by mylovetop** [comment]
![image](https://user-images.githubusercontent.com/1885713/176064534-522fa3bf-705b-4592-8023-14c4f8dfbe0c.png)
![image](https://user-images.githubusercontent.com/1885713/176064551-2c1372f5-a218-41ae-abdc-9d0e536780c9.png)

**Comment by mylovetop** [comment]
![image](https://user-images.githubusercontent.com/1885713/176064681-4b025c74-0351-4ef9-89f8-a55ee84ff570.png)

**Comment by jperedadnr** [comment]
You are using GraalVM for Windows 32 bits?
```
... '-ID:\app\jdk\graalvm\graalvm-ce-java17-22.1.0\include\win32'...
fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64']
```

Please follow https://docs.gluonhq.com/#platforms_windows
