### ISSUE TITLE
help me！  error, no such algoritm: ECDSA for provider BC

### ISSUE THREAD

**Issue by wonderfulLand** [gluonhq/gluon-samples#155]
![7c6b3df6-b423-4d03-98c7-fcfeadf1f280](https://user-images.githubusercontent.com/15264519/188543417-bc9cffc5-09f5-4e9a-8fe6-f0e29316ae9d.jpg)

1. run environment:  graalvm version 22.1.0,   native-image version 22.1
   gluonfx plugin version:
   
<plugin>
    <groupId>com.gluonhq</groupId>
    <artifactId>gluonfx-maven-plugin</artifactId>
    <version>1.0.15</version>
    <configuration>
        <mainClass>your.mainClass</mainClass>
    </configuration>
</plugin>

2.  error detail desc:

     when I  run my application in graalvm ，it is ok。   
     when I run my application in "mvn gluonfx:run", it is ok.  
     when I run my application im "mvn gluonfx:build" and then run in  “gluonfx:nativerun” ，my application is error。

3. i want to run my application in native image。  What should I do?

**Comment by ctoabidmaqbool** [comment]
It's alway good to fist run `gluonfx:runagent` and test your application for every single case. Then build using `gluonfx:build`.

[gluonfx:runagent](https://docs.gluonhq.com/#_gluonfxrunagent) task add some configuration files for grallvm native image feature.

**Comment by wonderfulLand** [comment]
> It's alway good to fist run `gluonfx:runagent` and test your application for every single case. Then build using `gluonfx:build`.
> 
> [gluonfx:runagent](https://docs.gluonhq.com/#_gluonfxrunagent) task add some configuration files for grallvm native image feature.

execute "gluonfx:runagent" is ok,   execute "gluonfx:nativerun" is error

**Comment by wonderfulLand** [comment]
add external err info:

![82090~UYQHE`2TZ`%_)O4DF](https://user-images.githubusercontent.com/15264519/188651314-26af1392-7009-4763-936d-9ad5512213aa.png)


[周二 9月 06 21:39:39 CST 2022][信息] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[周二 9月 06 21:39:43 CST 2022][信息] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[周二 9月 06 21:39:53 CST 2022][信息] [SUB] ========================================================================================================================
[周二 9月 06 21:39:53 CST 2022][信息] [SUB] GraalVM Native Image: Generating 'com.matj.smartwallet.ui.application.mainapplication' (shared library)...
[周二 9月 06 21:39:53 CST 2022][信息] [SUB] ========================================================================================================================
[周二 9月 06 21:39:59 CST 2022][信息] [SUB] [1/7] Initializing...                                                                                   (11.2s @ 0.15GB)
[周二 9月 06 21:39:59 CST 2022][信息] [SUB]  Version info: 'GraalVM 22.1.0 Java 17 EE'
[周二 9月 06 21:39:59 CST 2022][信息] [SUB]  C compiler: cl.exe (microsoft, x64, 19.33.31629)
[周二 9月 06 21:39:59 CST 2022][信息] [SUB]  Garbage collector: Serial GC
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] [2/7] Performing analysis...  [*]                                                                       (38.6s @ 1.21GB)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]   10,933 (88.10%) of 12,410 classes reachable
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]   18,286 (63.37%) of 28,855 fields reachable
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]   52,081 (65.07%) of 80,035 methods reachable
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]      512 classes,   144 fields, and   973 methods registered for reflection
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.bouncycastle.jce.provider.BouncyCastleProvider are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=org.bouncycastle.jce.provider.BouncyCastleProvider.
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.bouncycastle.jce.provider.BouncyCastleProvider are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=org.bouncycastle.jce.provider.BouncyCastleProvider.
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:135)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:582)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObject$3(ImageHeapScanner.java:272)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]     ... 10 more
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] ------------------------------------------------------------------------------------------------------------------------
[周二 9月 06 21:40:38 CST 2022][信息] [SUB]                         5.6s (10.6% of total time) in 28 GCs | Peak RSS: 3.87GB | CPU load: 5.08
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] ========================================================================================================================
[周二 9月 06 21:40:38 CST 2022][信息] [SUB] Failed generating 'com.matj.smartwallet.ui.application.mainapplication' after 50.3s.
[周二 9月 06 21:40:39 CST 2022][信息] [SUB] Error: Image build request failed with exit status 1
[周二 9月 06 21:40:39 CST 2022][严重] Process compile failed with result: 1
Check the log files under E:\ideaProjects\SmartWallet\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
[周二 9月 06 21:40:39 CST 2022][信息] Logging process [compile] to file: E:\ideaProjects\SmartWallet\target\gluonfx\log\process-compile-1662471639761.log
[周二 9月 06 21:40:39 CST 2022][严重] Compiling failed.
[周二 9月 06 21:40:39 CST 2022][严重] Compiling failed.
Check the log files under E:\ideaProjects\SmartWallet\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:03 min
[INFO] Finished at: 2022-09-06T21:40:39+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.15:compile (default-cli) on project smartwallet: Compiling failed -> [Help 1]

**Comment by wonderfulLand** [comment]
it is ok with    https://docs.gluonhq.com/#_build_time_initialization
