### ISSUE TITLE
Native image icon

### ISSUE THREAD

**Issue by Snoopy137** [gluonhq/gluon-samples#157]
I'm bulding an application for android and linux and I have 2 issues, one is that setting the png image as stated on the documentation but the application still shows the default gluon icon when launched in both linux system and android.
Second issue is that the package goal for linux has no output, the goal executes without errors but does not generate any files
This is the structure of the project
./src
├── android
│   ├── AndroidManifest.xml
│   ├── listadossn.png
│   └── res
│       ├── mipmap-hdpi
│       │   └── listadossn.png
│       ├── mipmap-hdpi.png
│       ├── mipmap-ldpi
│       │   └── listadossn.png
│       ├── mipmap-mdpi
│       │   └── listadossn.png
│       ├── mipmap-xhdpi
│       │   └── listadossn.png
│       ├── mipmap-xxhdpi
│       │   └── listadossn.png
│       └── mipmap-xxxhdpi
│           └── listadossn.png
├── listadossn.png
└── main
    ├── java
    │   └── com
    │       └── decssoft
    │           ├── DrawerManager.java
    │           ├── Testing.java
    │           └── views
    │               ├── PrimaryPresenter.java
    │               ├── PrimaryView.java
    │               ├── SecondaryPresenter.java
    │               └── SecondaryView.java
    └── resources
        ├── com
        │   └── decssoft
        │       ├── style.css
        │       └── views
        │           ├── primary.css
        │           ├── primary.fxml
        │           ├── secondary.css
        │           └── secondary.fxml
        └── listadossn.png

**Comment by jperedadnr** [comment]
As you can see [here](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/app/src/main/AndroidManifest.xml#L6), the default manifest uses `android:icon="@mipmap/ic_launcher"`, so either you rename your resources to `ic_launcher.png`, or modify your custom manifest with `android:icon="@mipmap/listadossn"`.

As for Linux, the package goal doesn't do anything, as the installer is not supported yet. It is on Windows and macOS.

**Comment by Snoopy137** [comment]
Hi jperedadnr, thanks for answering, I'm trying what you said right now.
What about the icon for the linux desktop app? is that something that will be include on the package goal or is there a workaround to set a custom icon?

**Comment by jperedadnr** [comment]
Once installers for Linux are supported, you will be able to set an icon.

**Comment by Snoopy137** [comment]
Thanks! I'm closing this one
