### ISSUE TITLE
build error LNK2001 ,Java_com_sun_management_internal_OperatingSystemImpl_getTotalMemorySize0; Java_com_sun_management_internal_OperatingSystemImpl_initialize0

### ISSUE THREAD

**Issue by 19chang19** [gluonhq/gluon-samples#163]
After compile, the link has an error.
**Using:**
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

**output:**
camera.app.obj : error LNK2001: 无法解析的外部符号 Java_com_sun_management_internal_OperatingSystemImpl_getTotalMemorySize0
camera.app.obj : error LNK2001: 无法解析的外部符号 Java_com_sun_management_internal_OperatingSystemImpl_initialize0

**Comment by geniusdz** [comment]
this error resolve？
