### ISSUE TITLE
build javafx native fail，help!

### ISSUE THREAD

**Issue by showfake** [gluonhq/gluon-samples#174]
this is my Environment Settings
![Snipaste_2023-10-22_18-18-10](https://github.com/gluonhq/gluon-samples/assets/81205841/18cba169-8472-4dd8-a9fd-e51e994f470a)
![Snipaste_2023-10-22_18-18-41](https://github.com/gluonhq/gluon-samples/assets/81205841/6f09ea4f-0d43-4775-90f6-6cdba2832986)
I'm sure there's nothing wrong with my environment setup；Because I can successfully build graalvm official helloworld demo，But my HelloFX to build the gluon-samples failed，The failure prompt is：
Could not detect GraalVM version, stopping now.
Check the log files under D:\project\gluon-samples\HelloFX\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
java.io.IOException: Couldn't determine GraalVM version
![Snipaste_2023-10-22_18-25-07](https://github.com/gluonhq/gluon-samples/assets/81205841/a56a6b3a-e1d0-4e13-ad00-7b486550025a)
Who can tell me how to operate this in order to successfully build the native mirror image?
This problem is too torture, many of my friends and I can't solve this problem, which makes me feel very frustrated to learn javafx and GraalVM
If possible, please explain in detail as much as possible, thanks

**Comment by jperedadnr** [comment]
Gluon [docs](https://docs.gluonhq.com/#platforms_windows) recommend using Gluon's GraalVM build from here https://github.com/gluonhq/graal/releases/latest.
GluonFX plugin doesn't support JDK 21 yet, so GraalVM 21 won't work, and you still need 22.1.0.1-Final.

However, work is being done in Substrate and once this [PR](https://github.com/gluonhq/substrate/pull/1236) is merged, 21 will be supported.
