### ISSUE TITLE
BUILD FAILURE on windows, during or after [SUB] [6/7] Compiling methods...

### ISSUE THREAD

**Issue by maverickGameowmancing** [gluonhq/gluon-samples#176]
Hello,
I am trying to compile the HelloWorld project on windows but the compilation fails with with result: 1
the logfile 
gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\log\client-debug0.log
ends with the following:

```
[Sat Nov 18 14:43:59 CET 2023][INFO] [SUB] ========================================================================================================================
[Sat Nov 18 14:43:59 CET 2023][INFO] [SUB] GraalVM Native Image: Generating 'hello.helloworld' (shared library)...
[Sat Nov 18 14:43:59 CET 2023][INFO] [SUB] ========================================================================================================================
[Sat Nov 18 14:44:05 CET 2023][INFO] [SUB] [1/7] Initializing...                                                                                    (7.7s @ 0.17GB)
[Sat Nov 18 14:44:05 CET 2023][INFO] [SUB]  Version info: 'GraalVM 22.1.0.1 Java 17 CE'
[Sat Nov 18 14:44:05 CET 2023][INFO] [SUB]  C compiler: cl.exe (microsoft, x64, 19.29.30040)
[Sat Nov 18 14:44:05 CET 2023][INFO] [SUB]  Garbage collector: Serial GC
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB] [2/7] Performing analysis...  [**************]                                                          (20.2s @ 1.00GB)
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB]    5,999 (87.33%) of  6,869 classes reachable
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB]    7,602 (52.97%) of 14,351 fields reachable
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB]   27,388 (55.85%) of 49,035 methods reachable
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB]      392 classes,   102 fields, and 1,029 methods registered for reflection
[Sat Nov 18 14:44:25 CET 2023][INFO] [SUB]       99 classes,    81 fields, and   108 methods registered for JNI access
[Sat Nov 18 14:44:27 CET 2023][INFO] [SUB] [3/7] Building universe...                                                                               (1.4s @ 1.39GB)
[Sat Nov 18 14:44:28 CET 2023][INFO] [SUB] [4/7] Parsing methods...      [*]                                                                        (1.1s @ 1.96GB)
[Sat Nov 18 14:44:30 CET 2023][INFO] [SUB] [5/7] Inlining methods...     [****]                                                                     (1.5s @ 2.58GB)
[Sat Nov 18 14:44:44 CET 2023][INFO] [SUB] [6/7] Compiling methods...    [****]                                                                    (14.1s @ 2.35GB)
v 18 14:44:47 CET 2023][INFO] [SUB] 
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]                         3.7s (7.3% of total time) in 25 GCs | Peak RSS: 4.45GB | CPU load: 5.81
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB] Produced artifacts:
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]  \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld.h (header)
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]  \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\graal_isolate.h (header)
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]  \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld_dynamic.h (header)
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]  \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\graal_isolate_dynamic.h (header)
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB]  \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld.build_artifacts.txt
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB] ========================================================================================================================
[Sat Nov 18 14:44:47 CET 2023][INFO] [SUB] Finished generating 'hello.helloworld' in 49.9s.
[Sat Nov 18 14:44:48 CET 2023][FINE] Result for compile: 1
v 18 14:44:48 CET 2023][SEVERE] Process compile failed with result: 1
Check the log files under \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
[Sat Nov 18 14:44:48 CET 2023][INFO] Logging process [compile] to file: \gluon-samples\HelloWorld\target\gluonfx\log\process-compile-1700315088428.log
[Sat Nov 18 14:44:48 CET 2023][SEVERE] Compiling failed.
Check the log files under \gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
```

But i dont find a hint on whats going wrong.

**Comment by jperedadnr** [comment]
post `\gluon-samples\HelloWorld\target\gluonfx\log\process-compile-1700315088428.log`?

**Comment by maverickGameowmancing** [comment]
Hey,
thank you very much, that solved it. I could find the cause by looking into the process-compile-1700315088428.log file: there is an issue with my visual studio setup.

A quick fix, via which the compilation did work and produce a functional .exe was to create the missing file:
C:\Users\me\AppData\Local\Temp\_MEI252082\condabin\conda_hook.bat

Content of \gluon-samples\HelloWorld\target\gluonfx\log\process-compile-1700315088428.log was:

`Process
=======
compile

Command Line
============
\programs\graalvm\graalvm-svm-java17-windows-gluon-22.1.0.1-Final\bin\native-image.cmd "-Djdk.internal.lambda.eagerlyInitialize=false" --no-server -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExceptionStackTraces -H:-DeadlockWatchdogExitOnTimeout "-H:DeadlockWatchdogInterval=0" -H:+RemoveSaturatedTypeFlows -H:+ExitAfterRelocatableImageWrite "--features=org.graalvm.home.HomeFinderFeature" "-H:TempDirectory=\intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\tmp" "-H:EnableURLProtocols=http,https" "-H:ReflectionConfigurationFiles=\intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\reflectionconfig-x86_64-windows.json" "-H:JNIConfigurationFiles=\intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\jniconfig-x86_64-windows.json" "-H:ResourceConfigurationFiles=\intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\resourceconfig-x86_64-windows.json" "-Dsvm.platform=org.graalvm.nativeimage.Platform$WINDOWS_AMD64" -cp "C:\Users\me\.m2\repository\com\gluonhq\substrate\0.0.60\substrate-0.0.60.jar;\intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\tmp\classpathJar.jar" hello.HelloWorld

Output
======
'"C:\Users\me\AppData\Local\Temp\_MEI252082\condabin\conda_hook.bat"' is not recognized as an internal or external command,
operable program or batch file.
Warning: Ignoring server-mode native-image argument --no-server.
========================================================================================================================
GraalVM Native Image: Generating 'hello.helloworld' (shared library)...
========================================================================================================================
[1/7] Initializing...                                                                                    (7.7s @ 0.17GB)
 Version info: 'GraalVM 22.1.0.1 Java 17 CE'
 C compiler: cl.exe (microsoft, x64, 19.29.30040)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [**************]                                                          (20.2s @ 1.00GB)
   5,999 (87.33%) of  6,869 classes reachable
   7,602 (52.97%) of 14,351 fields reachable
  27,388 (55.85%) of 49,035 methods reachable
     392 classes,   102 fields, and 1,029 methods registered for reflection
      99 classes,    81 fields, and   108 methods registered for JNI access
[3/7] Building universe...                                                                               (1.4s @ 1.39GB)
[4/7] Parsing methods...      [*]                                                                        (1.1s @ 1.96GB)
[5/7] Inlining methods...     [****]                                                                     (1.5s @ 2.58GB)
[6/7] Compiling methods...    [****]                                                                    (14.1s @ 2.35GB)

------------------------------------------------------------------------------------------------------------------------
                        3.7s (7.3% of total time) in 25 GCs | Peak RSS: 4.45GB | CPU load: 5.81
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 \intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld.h (header)
 \intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\graal_isolate.h (header)
 \intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld_dynamic.h (header)
 \intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\graal_isolate_dynamic.h (header)
 \intellij\community_edition\projects\gluon-samples\HelloWorld\target\gluonfx\x86_64-windows\gvm\HelloWorld\hello.helloworld.build_artifacts.txt
========================================================================================================================
Finished generating 'hello.helloworld' in 49.9s.


Result
======
result: 1`
