### ISSUE TITLE
MySQL JDBC Driver in Native Image with GraalVM

### ISSUE THREAD

**Issue by ejifloy** [gluonhq/gluon-samples#182]
### Missing Resource Bundle for MySQL JDBC Driver in Native Image with GraalVM
At the moment I'm developing a native desktop-app using GraalVM and GluonFX. When i try to deploy the app and connect to the database, I get an error and the program exits. I created a minimal project-setup which reproduces the error.  

#### Expected behavior:
The application successfully starts and connects to a local MySQL database using the MySQL JDBC driver in a native image created with GraalVM via the GluonFX plugin.

#### Actual behavior:
The application fails at runtime with the following error message:
```
Caused by: java.lang.RuntimeException: Can't load resource bundle due to underlying exception java.util.MissingResourceException: Can't find bundle for base name com.mysql.cj.LocalizedErrorMessages, locale de_DE
```
The exception indicates that the `LocalizedErrorMessages` resource bundle for the MySQL JDBC driver cannot be found, preventing the application from establishing the connection to the database.

#### Information about the Issue:
- **GluonFX Plugin Version**: 1.0.22
- **GraalVM**: Using the GraalVM native image build process via GluonFX.
- **MySQL JDBC Driver**: Version 8.3.0, with database/scheme "test"
- **Locale**: `de_DE`
- **Java Version**: 
```
java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)
```

#### Steps to reproduce the behavior:
1. Clone the repository: https://github.com/ejifloy/JavaFX-App-with-GluonFX-GraalVM
2. Configure the `pom.xml` properties if needed.
3. To create the native app, use the “[x64 Native Tools Command Prompt](https://docs.gluonhq.com/#platforms_windows)” from Visual Studio.
```
cmd.exe /k "<path to VS2019>\VC\Auxiliary\Build\vcvars64.bat"
```
4. Run with the native-image-agent to generate the configuration files (reflection, JNI, resource, ...) 
```
mvn gluonfx:runagent
```
5. Attempt to build a native image with GraalVM using the GluonFX Maven plugin.
```
mvn gluonfx:build
```
6. Run the native image using the following commands:
```
mvn gluonfx:nativerun
```
7. Observe the `MissingResourceException` for the resource bundle `com.mysql.cj.LocalizedErrorMessages`.

---
I'm still learning to use GraalVM and GluonFX and can't manage to fix this problem yet...

**Comment by ctoabidmaqbool** [comment]
@ejifloy 
Before making native image, it's always batter to do run [agent](https://docs.gluonhq.com/#_gluonfxrunagent) e.g.
```
mvn gluonfx:runagent
```
It will search for necessory native image configurations.

**Comment by ejifloy** [comment]
> @ejifloy Before making native image, it's always batter to do run [agent](https://docs.gluonhq.com/#_gluonfxrunagent) e.g.
> 
> ```
> mvn gluonfx:runagent
> ```
> 
> It will search for necessory native image configurations.

Thank you for the advice. Unfortunately it's still not working... I'm receiving:

```
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:356)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:208)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1428)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at java.sql.DriverManager.getConnection(DriverManager.java:681)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at java.sql.DriverManager.getConnection(DriverManager.java:229)
[Mo. Sept. 09 20:09:57 MESZ 2024][INFORMATION] [SUB]    at hellofx.HelloFXML.lambda$start$0(HelloFXML.java:29)
[...]
```

**Comment by ctoabidmaqbool1** [comment]
I have forked you project, do some changes, it's works like a charm!
https://github.com/ctoabidmaqbool/JavaFX-App-with-GluonFX-GraalVM-fork

```
java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment GraalVM 22.1.0.1 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM 22.1.0.1 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```

Make sure, use latest GraalVM: https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final

and Latest `Gluon Maven Plugin` e.g.: **1.0.23**

**Comment by ctoabidmaqbool** [comment]
@ejifloy ALSO CHECK IF SIMPLE JAVAFX PROGRAM WORKS WELL (E.G. `mvn gluonfx:run`)

**Comment by ejifloy** [comment]
So I did a second test with the sample-project. Here is the result:

| **Feature**                            | **MariaDB (3.0.5)** | **MySQL (8.3.0)**  |
|----------------------------------------|---------------------|--------------------|
| **Run within IDE**                     | ✔️                  | ✔️                 |
| **mvn javafx:run**                     | ✔️                  | ✔️                 |
| **mvn gluonfx:run**                    | ✔️                  | ✔️                 |
| **mvn gluonfx:runagent**               | ✔️                  | ✔️                 |
| **mvn gluonfx:build**                  | ✔️                  | ✔️                 |
| **mvn gluonfx:nativerun**              | ✔️                  | ❌                 |

The problem arises, when using the mysql-driver during nativerun. The native compilation works, but when I try to connect to the database, it throws an error.

To resolve this Problem I have taken following steps:

1. **Plugin Configuration Adjustments**:
   The **gluonfx-maven-plugin** was modified to include reflection entries, resource lists, and bundle lists for MySQL JDBC to ensure that all necessary resources and classes are available at runtime.

   Here is the updated configuration:

   ```xml
   <plugin>
       <groupId>com.gluonhq</groupId>
       <artifactId>gluonfx-maven-plugin</artifactId>
       <version>${gluonfx.maven.plugin.version}</version>
       <configuration>
           <verbose>true</verbose>
           <target>${gluonfx.target}</target>
           <mainClass>${main.class}</mainClass>
           <appIdentifier>${app.identifier}</appIdentifier>
           <releaseConfiguration>
               <vendor>Gluon</vendor>
               <description>${app.description}</description>
               <packageType>${package.type}</packageType>
           </releaseConfiguration>
           <reflectionList>
               <list>com.mysql.cj.protocol.ExportControlled</list>
               <list>com.mysql.cj.protocol.a.NativeProtocol</list>
               <list>com.mysql.cj.jdbc.ConnectionImpl</list>
               <list>com.mysql.cj.jdbc.NonRegisteringDriver</list>
               <list>com.mysql.cj.NativeSession</list>
           </reflectionList>
           <resourcesList>
               <list>META-INF/services/*</list>
               <list>com/mysql/cj/configurations/*</list>
               <list>com/mysql/cj/*</list>
           </resourcesList>
           <bundlesList>
               <list>com.mysql.cj.LocalizedErrorMessages</list>
           </bundlesList>
           <runtimeArgs>
               <runtimeArg>--initialize-at-run-time=com.mysql.cj.jdbc</runtimeArg>
               <runtimeArg>--report-unsupported-elements-at-runtime</runtimeArg>
           </runtimeArgs>
       </configuration>
   </plugin>
   ```

   - **Reflection Entries**: Added all MySQL-related classes such as `ExportControlled`, `NativeProtocol`, `ConnectionImpl`, `NonRegisteringDriver`, and `NativeSession` to allow them to be initialized at runtime.
   - **Resources List**: Ensured that resources inside `META-INF/services/` and the MySQL configurations are included.
   - **Bundles List**: Added `com.mysql.cj.LocalizedErrorMessages` to ensure the localized error messages are available for MySQL JDBC.

2. **Reflection Configuration**:
   The **reflection-config.json** was extended to include more MySQL classes to handle all declared fields, methods, and constructors.

   ```json
   {
     "name": "com.mysql.cj.jdbc.NonRegisteringDriver",
     "allDeclaredFields": true,
     "allPublicFields": true,
     "allDeclaredMethods": true,
     "allPublicMethods": true,
     "allDeclaredConstructors": true,
     "allPublicConstructors": true
   },
   {
     "name": "com.mysql.cj.protocol.a.NativeProtocol",
     "allDeclaredFields": true,
     "allPublicFields": true,
     "allDeclaredMethods": true,
     "allPublicMethods": true,
     "allDeclaredConstructors": true,
     "allPublicConstructors": true
   }
   ```

3. **Runtime Arguments**:
   - Added `--initialize-at-run-time` for **MySQL classes** to allow the MySQL JDBC driver to work correctly within a GraalVM native image.
   - Added `--report-unsupported-elements-at-runtime` for better debugging and visibility of unsupported features.

Despite these steps, the issue persists **only for native execution with MySQL**. The MariaDB configuration, in contrast, works perfectly across all environments. I have branched the sample project, so there exists a version of MariaDB and MySQL usage.
