### ISSUE TITLE
Upload samples to Play Market

### ISSUE THREAD

**Issue by Mart-Bogdan** [gluonhq/gluon-samples#21]
Why should I build it manually ualy, and struggle to run?

Please upload sample applications to Play Market.

**Comment by eugener** [comment]
The main point of samples is to learn how to write and build such applications.

**Comment by Mart-Bogdan** [comment]
@eugener I disagree.
When person desides should he lern thing, he wonts to test it on his device, withput need to set-up developemebnt environment, etc.

I'd like to know load time of application, for example.
Would it crash, or run smopthly, etc.

**P.S.** Gonna user Flutter / v-play
Seems far more friendly.
