### ISSUE TITLE
Notes sample app compilation error.

### ISSUE THREAD

**Issue by tpc-it** [gluonhq/gluon-samples#25]
I opened the "notes" sample in IntelliJ, opened the Gradle window, found Tasks->application->run and double-clicked it. I expected it to run.

I did the same in Eclipse and got the same error. 

This is from IntelliJ.

9:42:26 PM: Executing task 'run'...

> Task :compileJava
C:\Users\Tim\Documents\railtrailmusic\gluon-samples-master\notes\src\main\java\com\gluonhq\notesapp\service\Service.java:44: error: package javax.annotation is not visible
import javax.annotation.PostConstruct;
            ^
  (package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)

**Comment by abhinayagarwal** [comment]
Hi,

Can you please add the JDK details?

**Comment by tpc-it** [comment]
I was using 10.0.2 with the language level set to "8 - Lambdas, type annotations, etc."  

jdk1.8.0_111 does not have any problems.  Apparently version 10 has some library changes that dialing back the language level cannot fix. 

My apologies for the false alarm.

**Comment by abhinayagarwal** [comment]
Currently all samples, unless explicitly mentioned to run against Gluon VM, will run only with JDK 8.
