### ISSUE TITLE
Shared Object or method to share information between views or controller

### ISSUE THREAD

**Issue by rafacastalla** [gluonhq/gluon-samples#26]
The question is how to share information between views or controller with a shared object or form? Please help me with an example.

**Comment by jperedadnr** [comment]
See the [Notes](https://github.com/gluonhq/gluon-samples/tree/master/notes) sample for a use case of having a model that can be shared between views, and a detailed [tutorial](http://docs.gluonhq.com/samples/notes/. 

If that is what you were looking for, feel free to close the issue.
