### ISSUE TITLE
SQLite sample does not work

### ISSUE THREAD

**Issue by bk322** [gluonhq/gluon-samples#37]
When I try SQLite sample via `./gradlew run` I get:
```
src/main/java/com/gluonhq/sqlite/GluonSQLite.java:32: error: package javafx.scene does not exist
```

**Comment by bk322** [comment]
It runs with Oracle's build of Java 8. I happen to have one installed from the old days:
```
sdk u java 8.0.201-oracle
```

**Comment by jperedadnr** [comment]
Yes, all the samples that use jfxmobile plugin 1.3.17 require Java 1.8. 
For Java 11+, have a look at the Gluon Client plugin https://github.com/gluonhq/client-samples
