### ISSUE TITLE
Why can't make the mobile installation simple and easy? 

### ISSUE THREAD

**Issue by ivanooi** [gluonhq/gluon-samples#39]
Why until today, the Android Support Repository issues still exist? It should be an old issue and solved. Just make the Gluon mobile experience bad compare to others....

**Comment by johanvos** [comment]
I'm not 100% following. Where do you see references to Android Support Repository?

**Comment by ivanooi** [comment]
Hi, 
Thanks for the reply. THis is my 1st Gluon test run. I got this from here. The example

https://github.com/gluonhq/gluon-samples/tree/master/singleview-gluonvm

Thanks for the reply

**Comment by jperedadnr** [comment]
This is no longer an issue with the new Client plugin. Follow [documentation](https://docs.gluonhq.com/client/) for instructions.
