### ISSUE TITLE
SEVERE: javafx.platform is not defined. Desktop will be assumed by default.

### ISSUE THREAD

**Issue by sonica799** [gluonhq/gluon-samples#51]
package com.gluonhq.maps;

public class Main {

	public static void main(String[] args) {

		MapView map = new MapView();
	
	}
}

This is my main. Just a simple code. I'm getting javafx.platform issue in my eclipse console. I have added JavaFX library to my build path including other gluon jars. I don't have any other errors. Can you please help me with this?
![Annotation 2020-07-10 114612](https://user-images.githubusercontent.com/68098362/87122660-fa6a9180-c2a2-11ea-86f7-b8f05fc673f1.jpg)

**Comment by jperedadnr** [comment]
This is not an issue. It simply informs that the application is running on desktop. On mobile (iOS/Android) the `javafx.platform` is defined accordingly.
See https://github.com/gluonhq/attach/blob/master/modules/util/src/main/java/com/gluonhq/attach/util/Platform.java#L72, the level of warning now is not severe anymore.
