### ISSUE TITLE
Question / Clarification: Is it possible to include Native IOS Frameworks into Gluon?

### ISSUE THREAD

**Issue by LordTylus** [gluonhq/gluon-samples#62]
Hello there,

currently I am evaluating Gluon as a possible alternative to RoboVM.

The HelloWorldFXML sample seems to work fine, but since our app relies on interacting with the devices Camera and a few native IOS Frameworks I am now wondering if and how I would be able to continue using them with Gluon. 

With RoboVM (MobiVM) we were able to directly communicate with the Camera through their java native wrapper classes. And the same way also worked for native Frameworks if said wrapper classes were generated using MobiVMs bro-gen project.

Could you clarify and maybe point me to the right documentation, on how gluon handles this use case, if it is possible at all?

With kind regards

**Comment by jperedadnr** [comment]
See the HelloGluon sample, it uses [Gluon Attach](https://github.com/gluonhq/attach) to interact with camera, sensors and native API.

See the list of services that Attach provides. For instance, you can use `PicturesService` to access the camera. 

More services can be added if needed.

**Comment by LordTylus** [comment]
Hello,

thank you for your reply, I checked Gluon Attach before and inspected the PictureService. We are not sure if it fits our use case, as we do want to embed a camera preview directly into our view, to easily display additional information right next to it. The PictureService however does only seem to offer a takePicture and loadPicture method, but there does not seem to be any kind of embedded preview. However I have not tested it yet, so I cannot say for sure. 

Also I have not found a sample on how to include a Third-Party native Framework. Is there a documentation on how to create our own service implementations? Since the one Framework we cannot go without is proprietary we would need to figure out how to embed it into gluon if it is possible at all.

**Comment by jperedadnr** [comment]
You can create your own service (i.e using your native framework), in a similar way as Attach does.

Substrate will need to add that framework at the linking phase. So far we have a fixed list of frameworks: https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/target/IosTargetConfiguration.java#L63
Ideally, that should be extensible.

**Comment by scientificware** [comment]
@jperedadnr 
Is there a problem with PicturesService ?

> See the HelloGluon sample, it uses Gluon Attach to interact with camera, sensors and native API.
None sample of camera usages in HelloGluon.

I posted an issue few months ago, in the `attach` repository [Can't take a photo](https://github.com/gluonhq/attach/issues/259).
Nobody confirms or invalidates that.
