### ISSUE TITLE
How can I use desktop classifier to solve package errors on modular project?

### ISSUE THREAD

**Issue by UltraBurstXD** [gluonhq/gluon-samples#65]
I'm trying to build a simple sample using modular project features, but I'm facing many errors like:
```
error: package com.gluonhq.attach.util.impl is not visible
package com.gluonhq.attach.util.impl is declared in module com.gluonhq.attach.util, which does not export it
package com.sun.javafx is declared in module javafx.base, which does not export it to module Simple
package com.sun.javafx is not visible
package com.sun.javafx is declared in module javafx.base, which does not export it to module Simple
...
```
I heard something like `desktop classifier`, I don't know how should I use it on my Gradle based Project... Help, pls?

**Comment by jperedadnr** [comment]
You don't need to add the desktop classifier. The plugin will do it for the Attach services.
This is an issue tracker related to the existing samples. Better to post questions at StackOverflow providing enough information to reproduce the issue and get an answer.
