### ISSUE TITLE
HelloFX>>mvn client:build -Pandroid failed on macOS 10.15.6: Caused by: java.lang.NoSuchMethodException: sun.nio.ch.sctp.SctpChannelImpl.initIDs()

### ISSUE THREAD

**Issue by tonylyliu** [gluonhq/gluon-samples#66]
✘  ~/Desktop/Development/977-javafx-test-collections/002-gluon-samples/HelloFX   master ●  mvn client:build -Pandroid
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.gluonhq.samples:hellofx >---------------------
[INFO] Building hellofx 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.32:build (default-cli) @ hellofx ---
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.gluonhq.samples:hellofx >---------------------
[INFO] Building hellofx 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> client-maven-plugin:0.1.32:compile (default-cli) > process-classes @ hellofx >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofx ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< client-maven-plugin:0.1.32:compile (default-cli) < process-classes @ hellofx <<<
[INFO]
[INFO]
[INFO] --- client-maven-plugin:0.1.32:compile (default-cli) @ hellofx ---
[周三 9月 23 16:21:43 CST 2020][信息] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate

[周三 9月 23 16:21:45 CST 2020][信息] We will now compile your code for aarch64-linux-android. This may take some time.
[周三 9月 23 16:21:50 CST 2020][信息] [SUB] [hellofx.hellofx:53214]    classlist:   3,094.39 ms,  0.96 GB
[周三 9月 23 16:21:50 CST 2020][信息] [SUB] WARNING: Using an older version of the labsjdk-11.
[周三 9月 23 16:21:51 CST 2020][信息] [SUB] [hellofx.hellofx:53214]        (cap):     248.84 ms,  0.96 GB
[周三 9月 23 16:21:51 CST 2020][信息] [SUB] [hellofx.hellofx:53214]        setup:   1,874.72 ms,  0.96 GB
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] Fatal error:com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: sun.nio.ch.sctp.SctpChannelImpl.initIDs()
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:63)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.core.jdk.JNIRegistrationUtil.method(JNIRegistrationUtil.java:89)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.jdk.JNIRegistrationJavaNio.beforeAnalysis(JNIRegistrationJavaNio.java:96)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:693)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:693)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] Caused by: java.lang.NoSuchMethodException: sun.nio.ch.sctp.SctpChannelImpl.initIDs()
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	at com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:58)
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] 	... 13 more
[周三 9月 23 16:21:52 CST 2020][信息] [SUB] Error: Image build request failed with exit status 1
[周三 9月 23 16:21:52 CST 2020][严重] Process compile failed with result: 1
Check the log files under /Users/thomas/Desktop/Development/977-javafx-test-collections/002-gluon-samples/HelloFX/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[周三 9月 23 16:21:52 CST 2020][信息] Logging process [compile] to file: /Users/thomas/Desktop/Development/977-javafx-test-collections/002-gluon-samples/HelloFX/target/client/log/process-compile-1600849312124.log
[周三 9月 23 16:21:52 CST 2020][严重] Compiling failed.
Check the log files under /Users/thomas/Desktop/Development/977-javafx-test-collections/002-gluon-samples/HelloFX/target/client/aarch64-android/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.374 s
[INFO] Finished at: 2020-09-23T16:21:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.32:compile (default-cli) on project hellofx: Compiling failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.322 s
[INFO] Finished at: 2020-09-23T16:21:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.32:build (default-cli) on project hellofx: Error, client:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by tonylyliu** [comment]
Fatal error:com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: sun.nio.ch.sctp.SctpChannelImpl.initIDs()

**Comment by jperedadnr** [comment]
If you check the documentation for the [HelloFX sample](https://docs.gluonhq.com/client/0.1.32/#_target_android_233), you can't build for Android from Mac OS X.

**Comment by tonylyliu** [comment]
didn't notice that. Thank you for the support!

**Comment by tonylyliu** [comment]
Could it be possible to build android image with gluon mobile on Mac OS?
