### ISSUE TITLE
  mvn client:build -Pios stuck on macOS 15.6 for HelloFX project

### ISSUE THREAD

**Issue by tonylyliu** [gluonhq/gluon-samples#67]
✘  ~/Desktop/Development/977-javafx-test-collections/002-gluon-samples/HelloFX   master ●  mvn client:build -Pios
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.gluonhq.samples:hellofx >---------------------
[INFO] Building hellofx 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.32:build (default-cli) @ hellofx ---
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.gluonhq.samples:hellofx >---------------------
[INFO] Building hellofx 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> client-maven-plugin:0.1.32:compile (default-cli) > process-classes @ hellofx >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofx ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< client-maven-plugin:0.1.32:compile (default-cli) < process-classes @ hellofx <<<
[INFO]
[INFO]
[INFO] --- client-maven-plugin:0.1.32:compile (default-cli) @ hellofx ---
[周三 9月 23 16:22:03 CST 2020][信息] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate

====
>>>stuck here ....<<<<

**Comment by jperedadnr** [comment]
If you check the documentation for the [HelloFX sample](https://docs.gluonhq.com/client/0.1.32/#_target_android_233), you can't build for Android from Mac OS X.

**Comment by tonylyliu** [comment]
this is for ios build.

**Comment by jperedadnr** [comment]
See the log under `target/client/arm64-ios/gvm/log`, or alternatively add `<verbose>true</verbose>` to the plugin's configuration, and try again.
