### ISSUE TITLE
ColorPicker issue

### ISSUE THREAD

**Issue by XeonG** [gluonhq/gluon-samples#72]
If I add a ColorPicker to the default hello.fxml ..and use 'mvn javafx:run'  ... it works fine...

however if I do 'mvn client:build'  the build complete fine, however 'mvn client:run' results in the below error...

Can anyone explain...

[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellofxml >--------------------
[INFO] Building HelloFXML 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.33:run (default-cli) @ hellofxml ---
[Fri Oct 09 01:38:27 BST 2020][INFO] ==================== RUN TASK ====================
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB] Exception in Application start method
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at java.lang.Thread.run(Thread.java:834)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB] Caused by: javafx.fxml.LoadException:
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB] hellofx/hello.fxml
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2629)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2867)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2711)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2680)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2546)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2470)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3241)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3198)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3167)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3140)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3132)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at hellofx.HelloFXML.start(HelloFXML.java:42)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:101)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      ... 3 more
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB] Caused by: java.lang.ClassNotFoundException: javafx.scene.control.ColorPicker
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at java.lang.ClassLoader.loadClass(ClassLoader.java:233)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2935)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2924)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2865)
[Fri Oct 09 01:38:27 BST 2020][INFO] [SUB]      ... 22 more
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_reflectionlist, you need to add `javafx.scene.control.ColorPicker` to the `reflectionList`.

**Comment by XeonG** [comment]
even if I add that to the target/client/$arch-$os/gvm/reflectionconfig-$arch-$os.json,
  {
    "name" : "javafx.scene.control.ColorPicker"
  }
it just gets overwritten... why are we even having to add these things in manually anyway?

this is just awful workflow, obviously its not ready.

**Comment by jperedadnr** [comment]
It seems you didn't read the docs carefully, so let me read them for you step by step.

```
3.4.4. reflectionList
List of additional full qualified classes that will be added to the default reflection list, that already includes most of the JavaFX classes.
```

The `reflectionList` is an option that you can add to the configuration in the pom, like:

```
<plugin>
    <groupId>com.gluonhq</groupId>
    <artifactId>client-maven-plugin</artifactId>
    <version>0.1.33</version>
    <configuration>
        <mainClass>your.mainClass</mainClass>
        <reflectionList>
            <item>classname</item>
       </reflectionList>
...
```

The reason for needing this list has to do with the use of reflection. GraalVM's native-image needs to know in advance what classes are called reflectively. Read more here: https://github.com/oracle/graal/blob/master/substratevm/Reflection.md

Let's keep reading:
```
Note: The current list is added to a file that can be found under target/client/$arch-$os/gvm/reflectionconfig-$arch-$os.json.
```

When you run `mvn client:build`, a `reflectionconfig-$arch-$os.json` file is generated in the `target` folder, and you can see what classes/methods are already included. You can see that the list is quite long, but it is not 100% complete, and some JavaFX core classes are not included yet. 

If your class/method is not listed yet, you can add it to the `reflectionList`, as I suggested [here](https://github.com/gluonhq/gluon-samples/issues/72#issuecomment-711059733):

```
    <configuration>
        <mainClass>your.mainClass</mainClass>
        <reflectionList>
            <item>javafx.scene.control.ColorPicker</item>
       </reflectionList>
```

Note that you shouldn't modify a file created in `target`, running mvn again will always ignore your changes.

Finally:
```
For more advanced usage, read the [JNI and Reflection section](https://docs.gluonhq.com/client/0.1.33/#_jni_and_reflection).
```

There is another option to include classes/methods,  by creating a `reflectionconfig-$arch-$os.json` file under `src/main/resources/META-INF/substrate/config`, with something like:
```
[
  {
    "name":"javafx.scene.control.ColorPicker"
  }
]
```
You will see that after running `mvn client:build`, the content of this file will be added at the end of the `target/client/$arch-$os/gvm/reflectionconfig-$arch-$os.json` file.

You can use a Java [agent](https://github.com/oracle/graal/blob/master/substratevm/BuildConfiguration.md#assisted-configuration-of-native-image-builds) to find out what classes are used reflectively, or you can run some iterations to get all the missing classes into the reflection list.

**Comment by XeonG** [comment]
Ok thanks, that does work now, shame that Java agent can't be part of the build process to automatically add missing things into the reflection list.

Anyway that's working for the Windows build which is great, new issue is trying to get things working for the Android build https://github.com/gluonhq/gluon-samples/issues/66
