### ISSUE TITLE
Sample, HelloFXML not working in android.

### ISSUE THREAD

**Issue by Srijan-Sengupta** [gluonhq/gluon-samples#75]
Hello,

I cloned this repository, and navigated to the HelloFXML project. But when I ran `mvn client:install -Pandroid` after running `mvn client:build -Pandroid` and `mvn client:package`, I received Errors. The three log files are as follows :- 

[process-compile-1603030991075.log](https://github.com/gluonhq/gluon-samples/files/5399257/process-compile-1603030991075.log)
[process-link-1603031052053.log](https://github.com/gluonhq/gluon-samples/files/5399260/process-link-1603031052053.log)
[process-install-task-1603031233830.log](https://github.com/gluonhq/gluon-samples/files/5399261/process-install-task-1603031233830.log)

I had problem in the Install task. How can i fix it? Please help me.

**Comment by jperedadnr** [comment]
Can you try to install manually the apk? 

Plug your device and run on a terminal:
```
/path/to/androidSDK/platform-tools/adb install /home/srijan-sengupta/Workspace/Javafx/gluon-samples/HelloFXML/target/client/aarch64-android/gvm/android_project/app/build/outputs/apk/debug/app-debug.apk
```

See what errors do you get otherwise

**Comment by Srijan-Sengupta** [comment]
I have successfully installed but the **application isn't working**
![Screenshot from 2020-10-19 14-31-34](https://user-images.githubusercontent.com/54442785/96424183-f9d58580-1217-11eb-8960-c8280f5891cf.png)
![Screenshot from 2020-10-19 14-33-13](https://user-images.githubusercontent.com/54442785/96424225-0ce85580-1218-11eb-84a5-997e749c5f5c.png)

**Comment by jperedadnr** [comment]
then you need to find the stacktrace. Plug your device, run from terminal:

```
adb log-cat
```

and then run your application. You should see the output and then you can find out about what is causing the error.

**Comment by Srijan-Sengupta** [comment]
Here it is : 
[HelloFXML.log](https://github.com/gluonhq/gluon-samples/files/5400519/HelloFXML.log)

**Comment by Srijan-Sengupta** [comment]
Sorry, but I couldn't find the cause

**Comment by jperedadnr** [comment]
There you go:
```
D/AndroidRuntime( 2093): Shutting down VM
E/AndroidRuntime( 2093): FATAL EXCEPTION: main
E/AndroidRuntime( 2093): Process: com.gluonhq.samples.hellofxml, PID: 2093
E/AndroidRuntime( 2093): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getgrgid_r" referenced by "/data/app/com.gluonhq.samples.hellofxml-1/lib/arm64/libsubstrate.so"...
E/AndroidRuntime( 2093): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime( 2093): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 2093): 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
```

Please post details of the Client plugin (version), JDK version, GraalVM version, what Linux version are you building from, and what Android version are you running on.

**Comment by Srijan-Sengupta** [comment]
Info:
Linux destro : ubuntu 20.04
Client plugin : 0.1.31
GraalVM version : 20.2.0
Java verion : 11.0.8
Android : 5.1

**Comment by jperedadnr** [comment]
Try Client 0.1.33 (I don't think it's going to make a difference). Is it possible that you can try on a newer device? (Or post the apk here so I can try it)

**Comment by Srijan-Sengupta** [comment]
![Screenshot from 2020-10-19 15-00-34](https://user-images.githubusercontent.com/54442785/96427307-02c85600-121c-11eb-97f9-f8e0abf53158.png)

This may help you

**Comment by Srijan-Sengupta** [comment]
How must I post you as I have no other Android device

**Comment by jperedadnr** [comment]
You can drag the file here, to a new comment. If that doesn't work, upload it to Google Drive for instance, and share the link.

**Comment by Srijan-Sengupta** [comment]
Here : https://drive.google.com/file/d/1yj8b0cHysKlS_whJVYaARhcwQjLQMnDm/view?usp=sharing

**Comment by jperedadnr** [comment]
The app works fine for me (Pixel XL, Android 10).

**Comment by Srijan-Sengupta** [comment]
I think my one is arm architecture

**Comment by jperedadnr** [comment]
The apk has arm architecture, but requires 64 bits. It is possible that your device is 32 bits, and doesn't support 64.

**Comment by Srijan-Sengupta** [comment]
I did something bad to fix my issue and I found : 
 OUR APK:
![Screenshot from 2020-10-19 15-15-55](https://user-images.githubusercontent.com/54442785/96429498-a1ee4d00-121e-11eb-9580-e48ff52af4e9.png)
Normal Apk :
![Screenshot from 2020-10-19 15-19-34](https://user-images.githubusercontent.com/54442785/96429584-bc282b00-121e-11eb-88f5-963450fbe1b3.png)

**Comment by Srijan-Sengupta** [comment]
> The apk has arm architecture, but requires 64 bits. It is possible that your device is 32 bits, and doesn't support 64.

Might be but I have tested several apks on this mobile using Android Studio , with the same SDK

**Comment by jperedadnr** [comment]
Have you tested other apps with the Gluon Client plugin? That's the one that only builds for 64 bits.

**Comment by Srijan-Sengupta** [comment]
Yes I had tested an APK with Gluon Client but it also didn't work

**Comment by Srijan-Sengupta** [comment]
Can't I build the Apk for all the architectures?

**Comment by jperedadnr** [comment]
GluonFX plugin doesn't support ARM 32 bits
