### ISSUE TITLE
(Charm)ListView scrollbar problem

### ISSUE THREAD

**Issue by MakHoCheung** [gluonhq/gluon-samples#76]
I found the thumb size of scrollbar of  not only ListView but also CharmListView have a problem. When the ListCell in the ListView has different heights, the thumb 
size of scrollbar will change when scrolling.Sometime it is tall but sometime it is short. I want to simulate  the mobile UI like UITableView in iOS to show content. Can this problem be fixed?
![截屏2020-10-27 下午4 57 02](https://user-images.githubusercontent.com/22256775/97378916-7e05c800-18fe-11eb-907a-0e90706e2da1.png)
![截屏2020-10-27 下午4 57 29](https://user-images.githubusercontent.com/22256775/97378922-80682200-18fe-11eb-9a78-5dc6f0a6dda0.png)

**Comment by MakHoCheung** [comment]
The RecyclerView of Android also has the same problem.
https://stackoverflow.com/questions/46033473/recyclerview-with-items-of-different-height-scrollbar

**Comment by jperedadnr** [comment]
I don't think having cells with very different heights is wise (either ListView, CharmListView or even the RecyclerView). 

In case of the JavaFX ListView, the control has been designed to be virtualised providing a set of "real" cells that are reused to show the content of the list, and when you scroll, they are simply updated (via `updateItem`), and for each call, the scrollBars are recalculated (size, position). Calculations are based on regular content (in terms of more or less same height for every item).

However, if you have very tall items among short ones, the calculations will certainly fail. And anyway, from UI perspective, having very different cells can be confusing for the user.

My advise on this: provide uniform content for your List, and when needed create detail views where you can expand the content of the cell.
