### ISSUE TITLE
Provide CI-Builds (travis or github pipeline) for easy reproducibility

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/gluon-samples#77]
Please provide a travis / github-pipeline build for at least 1 of the mobile projects.

Every time I'm playing around with GluonMoible I get frustrated because the setup is quite complicated. 
So I usually avoid it. A simple CI build would drastically improve the situation for me and others.

A working reproducible build is better than any "classic text-based" documentation because it's correctness is verified and the build is also reusable for other projects.

I think this would make gluon mobile accessible to many more people.

**Comment by jperedadnr** [comment]
See https://gluonhq.com/use-github-actions-to-automate-your-gluon-build-and-release-cycle/
and check out https://github.com/gluonhq/hello-gluon-ci
