### ISSUE TITLE
${maven.home} is not specified as a directory

### ISSUE THREAD

**Issue by MillionStrengthKnowledge** [gluonhq/gluon-samples#81]
I try to execute mvn client:build -Pandroid, but I get this error:

Execution default-cli of goal com.gluonhq:client-maven-plugin:0.1.34:build failed: ${maven.home} is not specified as a directory: 'C:\Users\user01\javafx\gluon-samples-master\HelloFXML\EMBEDDED

How should I configure the project to get rid of this problem?

**Comment by jperedadnr** [comment]
You can't deploy to Android from Windows (unless you use WSL2). See https://docs.gluonhq.com/#platforms_android

Anyway, that is a Maven issue, you are running with the embedded maven from your IDE (Eclipse? Then see this [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=341120)). It is better to install and use an external Maven (3.6+)
