### ISSUE TITLE
mvn client:build fails with [javafx-web] WebView 

### ISSUE THREAD

**Issue by JinyKafe** [gluonhq/gluon-samples#85]
Dear team, 
I am not able to build a native image for Windows if I use a WebView component in my application. Without javafx-web module, I can build it successfully. 

The main exception message says
`[Thu Dec 10 20:41:19 UTC 2020][INFO] [SUB] Warning: Aborting stand-alone image build. com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javafx.scene.web.WebView`

The full exception stack trace can be seen in my Project's [GitHub Action runner here](https://github.com/JinyKafe/GluonClientWithWebview/runs/1533287934?check_suite_focus=true)

FYI: I can build and run the application with  mvn javafx:run
For compilation I used GraalVM 20.3.0.java11, JavaFX 15 and Java 11

The project is at disposal in GitHub [here](https://github.com/JinyKafe/GluonClientWithWebview) and  I also attached the source code to this ticket. 

[Exception_stacktrace.log](https://github.com/gluonhq/gluon-samples/files/5675571/Exception_stacktrace.log)

[GluonClientWithWebview-main.zip](https://github.com/gluonhq/gluon-samples/files/5675562/GluonClientWithWebview-main.zip)

Thank you very much for your answer and for all the magic work you are doing.
Best regards, 
Jan Kotek

**Comment by abhinayagarwal** [comment]
This is currently not supported and the progress can be tracked here: https://github.com/gluonhq/substrate/issues/515
