### ISSUE TITLE
"Graalvm-ce-java11-21.0.0" is corrupted and cannot be opened.

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluon-samples#87]
I downloaded the graalvm-ce-java11-21.0.0.
While running the "mvn client: build -Pios" command I always get the error described in the question title: "Graalvm-ce-java11-21.0.0" is corrupted and cannot be opened.
What should I do?

Thanks

**Comment by jperedadnr** [comment]
Make sure you download the proper link: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-darwin-amd64-21.0.0.tar.gz
Then extract the file, and make sure you set the `GRAALVM_HOME` to the path, like

```
export GRAALVM_HOME=/path/to/graalvm-ce-java11-21.0.0/Contents/Home
```

Then try again.

**Comment by websystemtechnology** [comment]
Thanks a lot, but I have the same problem

**Comment by jperedadnr** [comment]
Open a terminal and run:

```
cd Downloads 
wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-darwin-amd64-21.0.0.tar.gz
# make sure you get a file of around 446 MB

tar -zxvf graalvm-ce-java11-darwin-amd64-21.0.0.tar.gz
rm graalvm-ce-java11-darwin-amd64-21.0.0.tar.gz
graalvm-ce-java11-21.0.0/Contents/Home/bin/java -version
# see that it prints: openjdk version "11.0.10" 2021-01-19...

export GRAALVM_HOME=/User/<your_user>/Downloads/graalvm-ce-java11-21.0.0/Contents/Home/ 
```
then you should be able to run `mvn clean -Pios client:build`.

**Comment by websystemtechnology** [comment]
ok, I performed the steps from your previous message, but I get this error: "java.io.IOException: Path provided for GraalVM doesn't contain bin / native-image: /opt/graalvm-ce-java11-21.0.0/ Contents / Home"

**Comment by jperedadnr** [comment]
Is that happening when you run `mvn clean -Pios client:build`?
What plugin version are you using? 0.1.36 is the latest. 
The plugin will take care of installing `native-image`. Otherwise you can do it following the error message that is printed.

**Comment by websystemtechnology** [comment]
Sorry, the last error occurred because I was not using the latest version of the plugin. thanks a lot

**Comment by websystemtechnology** [comment]
Sorry, another question what is the target to use in the pom.xml to run the "mvn client: run" command on ios (I'm using a mac)?

<plugin>
	<groupId>com.gluonhq</groupId>
	<artifactId>client-maven-plugin</artifactId>
	<version>${client.plugin.version}</version>
	<configuration>
		<iosSignIdentity>Apple Development: xxx</iosSignIdentity>
		<iosProvisioningProfile>provision profile dev</iosProvisioningProfile>
		<target>ios</target>

**Comment by websystemtechnology** [comment]
-<-plugin->-
	-<-groupId->-com.gluonhq-<-/groupId->-
	-<-artifactId->-client-maven-plugin-<-/artifactId->-
	-<-version->-${client.plugin.version}-<-/version->-
	-<-configuration->-
		-<-iosSignIdentity->-Apple Development: xxx-<-/iosSignIdentity->-
		-<-iosProvisioningProfile->-ryme provision profile dev-<-/iosProvisioningProfile->-
		-<-target->-ios-<-/target->-
