### ISSUE TITLE
let mvn client:package -Pandroid fail gracefully when android is not installed properly

### ISSUE THREAD

**Issue by wlnirvana** [gluonhq/gluon-samples#89]
I happen to have installed the android 29 sdk but not build tools. (Because the latest version is 30, and installing sdk 29 in android studio does not automatically include the build tools by default). In this case, `mvn client:package -Pandroid` seems to run forever without any error message.

**Comment by jperedadnr** [comment]
The client plugin [checks](https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java#L150) for all required tools precisely during the `package` goal. 

You should have received a [message](https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/util/FileDeps.java#L163) about it.

Then another [message](https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/util/FileDeps.java#L472) informing you that it might take some time...

**Comment by wlnirvana** [comment]
Somehow I was not able to reproduce this problem. Build after deleting build tools for Android sdk 29 indeed generated `Required Android packages not found: [build-tools;29.0.3]`. Not sure what was the problem yesterday. So closing this issue for now.
