### ISSUE TITLE
mvn client:run doesn't work

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluon-samples#93]
Sorry, what is the target to use in the pom.xml to run the "mvn client: run" command on ios (I'm using a mac)?

-<-plugin->-
-<-groupId->-com.gluonhq-<-/groupId->-
-<-artifactId->-client-maven-plugin-<-/artifactId->-
-<-version->-${client.plugin.version}-<-/version->-
-<-configuration->-
-<-iosSignIdentity->-Apple Development: xxx-<-/iosSignIdentity->-
-<-iosProvisioningProfile->-ryme provision profile dev-<-/iosProvisioningProfile->-
-<-target->-ios???-<-/target->-

**Comment by jperedadnr** [comment]
Any of the samples uses as target `<target>ios</target>`, see for instance: https://github.com/gluonhq/gluon-samples/blob/master/HelloFX/pom.xml#L71

See also https://docs.gluonhq.com/#_target

**Comment by websystemtechnology** [comment]
Sorry, I have this error:
"Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)"
In the store I created the certificates for development only
